stages:
  - docker
  - test
  - deploy-nonprod
  - deploy-prod

docker:
  stage: docker
  script:
    - echo "hello"

test-nonprod:
  stage: test
  script:
    - echo "hello"

deploy-nonprod:
  stage: deploy-nonprod
  script:
    - echo "hello"

deploy-prod:
  stage: deploy-prod
  script:
    - echo "hello"
  
