# This file is strictly for development - Not to be used in production.
version: '3'
services:
  backend:
    restart: always
    build: theroast_backend
    volumes:
      - ./theroast_backend:/app
    ports:
      - 8000:8000
    environment:
      - ENV=nonprod