# This file is strictly for development - Not to be used in production.

version: '3'
services:
  backend:
    restart: always
    build: backend
    ports:
      - "5000:5000"
    environment:
      - TEST=HELLO